name: cisum
description: "A new Flutter project."
publish_to: 'none'
version: 2.1.31+104

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  super_drag_and_drop: ^0.8.9
  path: any
  audioplayers: ^5.2.1
  logger: ^2.1.0
  provider: ^6.1.2
  window_manager: ^0.3.8
  super_context_menu: ^0.8.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
