# 标签push到main或Workflow Bump结束时，构建并发布
on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows:
      - 'Bump'
    types:
      - completed

permissions:
  contents: write

name: Build And Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install create-dmg
        run: npm install -g create-dmg
      - name: 准备 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          architecture: x64
      - name: 启用 Flutter macOS 平台
        run: flutter config --enable-macos-desktop
      - name: 构建 macOS APP
        run: flutter build macos
      - name: 打包成 DMG
        continue-on-error: true
        run: |
          create-dmg build/macos/Build/Products/Release/快易知.app
      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: 'macOS'
          path: |
            *.dmg
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 下载构件
        uses: actions/download-artifact@v3

      - name: 检查文件
        run: ls -alhR

      - name: 读取版本号
        run: |

          # 读取pubspec.yaml文件中的版本号
          current_version=$(sed -n '/version:/s/version:[[:space:]]*//p' pubspec.yaml | tr -d ' \r')
          echo "当前版本号：$current_version"

          # 写入环境变量
          echo "tag=v$current_version" >> $GITHUB_ENV

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: |
            ./**/*.dmg
            ./**/*.zip
            ./**/*.exe
            ./**/*.AppImage
            ./**/*.snap
