# 准备工作：
# 1. AppStoreConnect网站-APP-用户和访问-集成-API，创建一个密钥，下载下来
# 2. base64 -i AuthKey_XXX.p8
# 3. GitHub Actions Secrets 添加
#   APP_STORE_CONNECT_KEY_BASE64
#   APP_STORE_CONNECT_KEY_ID
#   APP_STORE_CONNECT_KEY_ISSER_ID

on:
  push:
    branches:
      - test

name: Build With Sign

jobs:
  build_macOS:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 准备 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - run: flutter --version
      - run: dart --version
      - run: flutter precache --macos
      - run: flutter pub get
      - run: flutter build macos --config-only
      - uses: mxcl/xcodebuild@v1
        with:
          #   platform: macos
          working-directory: macos
          authentication-key-base64: ${{ secrets.APP_STORE_CONNECT_KEY_BASE64 }}
          authentication-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          authentication-key-issuer-id: ${{ secrets.APP_STORE_CONNECT_KEY_ISSER_ID }}
