# 标签push到main或Workflow Bump结束时，构建并发布

name: Release

on:
  push:
    branches:
      - test
    tags:
      - '*'
  workflow_run:
    workflows:
      - 'Bump'
    types:
      - completed

permissions:
  contents: write

env:
  tag: ${{ github.event.head_commit.id }}

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 准备 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - run: flutter --version
      - run: dart --version
      - run: flutter pub get
      # - run: flutter build apk --debug --split-per-abi

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 准备 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - run: flutter --version
      - run: dart --version
      - run: flutter pub get
      # - name: 上传构件
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: 'macOS'
      #     path: |
      #       *.dmg
      #     retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs:
      - build_windows
      - build_android
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: ls -alhR
      - name: 读取版本号
        run: |

          # 读取pubspec.yaml文件中的版本号
          current_version=$(sed -n '/version:/s/version:[[:space:]]*//p' pubspec.yaml | tr -d ' \r')
          echo "当前版本号：$current_version"

          # 写入环境变量
          echo "tag=v$current_version" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: |
            ./**/*.dmg
            ./**/*.zip
            ./**/*.exe
            ./**/*.pkg
            ./**/*.deb
            ./**/*.ipa
            ./**/*.AppImage
            ./**/*.snap
